import { useEffect, useState } from 'react'
import type { Place, StudyCondition } from '../types'
import { IconAlert, IconArrowLeft, IconCheck, IconClock, IconRefresh, IconSparkle, IconX } from '../components/Icons'
import { Badge, ProgressPanel } from '../components/UI'

export function FreshnessFlow({ place, condition, onClose, onUpdate, onReplace }: { place:Place; condition:StudyCondition; onClose:()=>void; onUpdate:(p:Place)=>void; onReplace:(old:Place)=>void }) {
  const [stage,setStage]=useState<'detail'|'checking'|'result'|'evidence'|'decision'>('detail')
  const [progress,setProgress]=useState(0)
  const isConflict=place.id==='restaurant-a' || place.status==='review' || place.status==='outdated'
  useEffect(()=>{if(stage!=='checking')return;setProgress(12);const a=setTimeout(()=>setProgress(42),450),b=setTimeout(()=>setProgress(74),900),c=setTimeout(()=>setProgress(100),1350),d=setTimeout(()=>setStage('result'),1650);return()=>[a,b,c,d].forEach(clearTimeout)},[stage])
  function header(title:string,subtitle:string){return <><div className="flow-nav"><button onClick={stage==='detail'?onClose:()=>setStage(stage==='decision'?'evidence':stage==='evidence'?'result':'detail')}><IconArrowLeft/></button><span>Freshness check</span><button onClick={onClose}><IconX/></button></div><div className="flow-title"><div className="brand">PINWISE</div><h1>{title}</h1><p>{subtitle}</p></div></>}
  return <div className="flow-screen">
    {stage==='detail' && <>{header(place.name,'Review practical information extracted from your saved source.')}<div className="flow-content"><section className="info-card"><div className="info-card-head"><strong>From saved post</strong><Badge status={condition==='aggregation'?'neutral':place.status}/></div><p>{place.savedInfo}</p><div className="meta-line"><IconClock/>Post age: {place.postAge}</div></section><section className="info-card soft"><strong>Source context</strong><p>{place.note}</p></section>{condition==='aggregation'?<button className="primary-button" onClick={()=>{onUpdate({...place,status:'unverified'});onClose()}}>Keep in itinerary</button>:<button className="primary-button" onClick={()=>setStage('checking')}>Check current information</button>}</div></>}
    {stage==='checking' && <>{header('Checking freshness','AI compares the saved post with more recent information.')}<div className="flow-content"><ProgressPanel title="Looking for recent evidence" subtitle="Official listings · recent reviews · current opening hours" progress={progress}/><section className="mini-list"><div><IconCheck/><span>Opening hours</span></div><div><IconCheck/><span>Closure status</span></div><div><IconCheck/><span>Reservation rules</span></div></section></div></>}
    {stage==='result' && <>{header(isConflict?'Needs review':'Looks current',isConflict?'AI found newer evidence that conflicts with the saved post.':'No meaningful conflict was found in recent evidence.')}<div className="flow-content"><section className={`warning-card ${isConflict?'':'good'}`}><div className="warning-icon">{isConflict?<IconAlert/>:<IconCheck/>}</div><span className="eyebrow">{isConflict?'POTENTIALLY OUTDATED':'CURRENT'}</span><h2>{isConflict?'Practical details changed':'Information still matches'}</h2><p><b>Saved:</b> {place.savedInfo}</p><p><b>Recent:</b> {place.recentInfo}</p><Badge status={isConflict?'review':'current'}>{isConflict?'Needs review':'Current'}</Badge></section><section className="info-card soft"><strong>Why AI {isConflict?'flagged it':'accepted it'}</strong><p>{isConflict?`The source is ${place.postAge} old and recent sources report changed practical details.`:'Recent sources agree with the saved information.'}</p><Badge status="ai">AI rationale</Badge></section>{isConflict?<button className="primary-button" onClick={()=>setStage('evidence')}>View supporting evidence</button>:<button className="primary-button" onClick={()=>{onUpdate({...place,status:'current'});onClose()}}>Keep in itinerary</button>}</div></>}
    {stage==='evidence' && <>{header('Compare recent evidence','See why the older saved information may no longer be reliable.')}<div className="flow-content evidence-stack"><EvidenceCard tone="current" title="Official listing · 3 days ago" copy={place.recentInfo}/><EvidenceCard tone="current" title="Recent review · 1 week ago" copy="Mentions the place now closes earlier and recommends booking ahead."/><EvidenceCard tone="old" title={`Saved post · ${place.postAge} ago`} copy={place.savedInfo}/><button className="primary-button" onClick={()=>setStage('decision')}>Decide what to do</button></div></>}
    {stage==='decision' && <>{header('Make the final choice','AI informs the decision but does not automatically remove the place.')}<div className="flow-content"><button className="decision-card" onClick={()=>{onUpdate({...place,status:'current',savedInfo:place.recentInfo});onClose()}}><div className="decision-icon keep"><IconCheck/></div><div><strong>Keep {place.name}</strong><p>Keep the place and use the updated practical information in the itinerary.</p></div></button><div className="or">OR</div><button className="decision-card" onClick={()=>onReplace(place)}><div className="decision-icon replace"><IconRefresh/></div><div><strong>Replace {place.name}</strong><p>Choose a nearby option with current information and preserve your final say.</p></div></button><div className="agency-note"><IconSparkle/><span>User decision is preserved when AI re-optimizes later.</span></div></div></>}
  </div>
}

function EvidenceCard({tone,title,copy}:{tone:'current'|'old';title:string;copy:string}){return <article className={`evidence-card ${tone}`}><div><strong>{title}</strong><Badge status={tone==='current'?'current':'unverified'}>{tone==='current'?'Recent':'Older'}</Badge></div><p>{copy}</p></article>}
